import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

type Props = {
  title: string;
};

const Home: NextPage<Props> = ({ title }) => {
  const cookie = fetch("/get-cookie", {
    method: "GET",
  });
  console.log(cookie);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>
        <div>
          <Link href={"./index2"}>to index2</Link>
        </div>
        <div>
          <p>{`current hash: ${process.env.NEXT_PUBLIC_BUILD_ID}`}</p>
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  return {
    props: {
      title: "top page",
    },
  };
};
